version: 2.1

jobs:
  build-and-test-ubuntu:
    docker:
      - image: 'redislabs/redisgears:edge'
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip unzip maven
      - checkout
      - run:
          name: Setup automation
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy3
      - run:
          name: Install and Configure mysql
          command: |
            apt-get update
            apt-get install -y mariadb-server-10.5
            service mariadb start
            /bin/bash ./setup-mysql
      - run:
            name: Install test dependencies
            command: |
              python3 -m pip install --upgrade pip setuptools
              python3 -m pip install -r pytest/requirements.txt
      - run:
          name: Test
          command: make tests
      - run:
          name: deploy maven artifact
          command: mvn -s .circleci.settings.xml -DskipTests deploy
      - persist_to_workspace:
          root: artifacts
          paths:
            - 'snapshot/*.jar'
            - 'release/*.jar'
  deploy_snapshots:
      docker:
        - image: redisfab/rmbuilder:6.0.9-x64-buster
      steps:
        - attach_workspace:
            at: artifacts
        - run:
            name: Deploy Snapshots to S3
            command: |
              python3 -m pip install awscli
              for f in artifacts/snapshot/*.jar; do
                aws s3 cp $f s3://redismodules/rghibernate/snapshots/ --acl public-read
              done
  deploy_release:
      docker:
        - image: redisfab/rmbuilder:6.0.9-x64-buster
      steps:
        - attach_workspace:
            at: artifacts
        - run:
            name: Deploy Snapshots to S3
            command: |
              python3 -m pip install awscli
              for f in artifacts/snapshot/*.jar; do
              for f in artifacts/release/*.jar; do
                aws s3 cp $f s3://redismodules/rghibernate/ --acl public-read
              done

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

on-master: &on-master
  filters:
    branches:
      only:
        - master
        - write_through_support

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

after-build-and-test: &after-build-and-test
  requires:
    - build-and-test-ubuntu

workflows:
  version: 2
  commit:
    jobs:
      - build-and-test-ubuntu:
          <<: *on-any-branch
      - deploy_snapshots:
          context: common
          <<: *after-build-and-test
          <<: *on-master
      - deploy_release:
          context: common
          <<: *after-build-and-test
          <<: *on-version-tags

  nightly:
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - build-and-test-ubuntu
