version: 2.1

commands: 
  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy3
            ./deps/readies/bin/getpy2
            python3 ./deps/readies/bin/system-setup.py

jobs:
  build-and-test-bionic:
      docker:
        - image: 'ubuntu:bionic'
      steps:
        - run:
            name: Setup executor
            command: |
              apt-get -qq update
              apt-get -q install -y git openssh-client curl ca-certificates make tar gzip python3-dev unzip python-pip maven
        - checkout
        - setup-automation
        - run:
            name: Install Redis
            command: ./deps/readies/bin/getredis --version 6
        - run:
            name: Install RLTest
            command: python3 -m pip install --no-cache-dir git+https://github.com/RedisLabsModules/RLTest.git@master docker sqlalchemy cx_Oracle cx-oracle
        - run:
            name: Install Oracle client
            command: /bin/bash install_oracle_driver.sh
        - run:
            name: Tests
            command: make tests

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

on-master: &on-master
  filters:
    branches:
      only: master

after-build-and-test: &after-build-and-test
  requires:
    - build-and-test-bionic

workflows:
  version: 2
  commit:
    jobs:
      - build-and-test-bionic:
          <<: *on-any-branch

  nightly:
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - build-and-test-bionic
