version: 2.1

commands:

  build-and-test:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip unzip maven
      - checkout
      - run:
          name: Setup automation
          command: |
            git submodule update --init --recursive
            ./deps/readies/bin/getpy3
      - run:
          name: Install and Configure mysql
          command: |
            apt-get update
            apt-get install -y mariadb-server-10.5
            service mariadb start
            /bin/bash ./setup-mysql
      - run:
            name: Install test dependencies
            command: |
              python3 -m pip install --upgrade pip setuptools
              python3 -m pip install -r pytest/requirements.txt
      - run:
          name: Test
          command: make tests
      - persist_to_workspace:
          root: artifacts
          paths:
            - 'snapshot/*.jar'
            - 'release/*.jar'

jobs:

  build_and_test:
    docker:
      - image: 'redislabs/redisgears:edge'
    steps:
      - build-and-test

  build_and_test_and_deploy:
    docker:
      - image: 'redislabs/redisgears:edge'
    steps:
      - build-and-test
      - run:
          name: deploy maven artifact
          command: mvn -s .circleci.settings.xml -DskipTests deploy


  deploy_snapshots:
      docker:
        - image: redisfab/rmbuilder:6.0.9-x64-buster
      steps:
        - attach_workspace:
            at: artifacts
        - run:
            name: Deploy Snapshots to S3
            command: |
              python3 -m pip install --upgrade pip
              python3 -m pip install awscli
              for f in artifacts/snapshot/*.jar; do
                aws s3 cp $f s3://redismodules/rghibernate/snapshots/ --acl public-read
              done
  deploy_release:
      docker:
        - image: redisfab/rmbuilder:6.0.9-x64-buster
      steps:
        - attach_workspace:
            at: artifacts
        - run:
            name: Deploy Snapshots to S3
            command: |
              python3 -m pip install --upgrade pip
              python3 -m pip install awscli
              for f in artifacts/release/*.jar; do
                aws s3 cp $f s3://redismodules/rghibernate/ --acl public-read
              done

not-on-integ-branch: &not-on-integ-branch
  filters:
    branches:
      ignore:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only:
        - master

on-integ-branch: &on-integ-branch
  filters:
    branches:
      only:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      ignore: /.*/

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

after-build-and-test-and-deploy: &after-build-and-test-and-deploy
  requires:
    - build_and_test_and_deploy

workflows:
  version: 2
  commit:
    jobs:
      # - build_and_test:
      #     <<: *not-on-integ-branch
      - build_and_test_and_deploy:
          context: common
          <<: *not-on-integ-branch
          # <<: *on-integ-branch
      - deploy_snapshots:
          context: common
          <<: *after-build-and-test-and-deploy
          <<: *on-integ-branch
      - deploy_release:
          context: common
          <<: *after-build-and-test-and-deploy
          <<: *on-version-tags

  nightly:
      triggers:
        - schedule:
            cron: "0 0 * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - build_and_test_and_deploy:
            context: common
