---

name: Integration

on:
  push:

  schedule:
    - cron: "5 5 * * *"

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.pip
            ~/.cache
            /var/cache/apt
          key: rghibernate-${{hashFiles('**/pom.xml')}}
      - name: start mariadb
        run: |
          docker run -d -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes -v `pwd`/setup-mysql:/docker-entrypoint-initdb.d/setup.sh -p 3306:3306 mariadb:10.4
          sleep 30
      - run: |
          pip install rltest
          make tests
        env:
          JVM_OPTS: -Xmx3200m
      - name: codecov
        run: |
           bash <(curl -s https://codecov.io/bash)
      - uses: s3-actions/s3cmd@v1.1
        with:
          provider: aws
          region: us-east-1
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: upload snapshots
        run: |
          s3cmd put -P artifacts/snapshot/*.jar s3://redismodules/rghibernate/snapshots/
