---

name: Integration

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.rst'
    branches:
      - master
      - '[0-9].[0-9]'
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]'

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: shut off exisiting mysql
        run:
          sudo service mysql stop
      - name: set up mariadb
        uses: getong/mariadb-action@v1.1
          host_port: 3306
          mysql database: test
          mysql user: demouser
          mysql password: "Password123!"
          mariadb version: '10.4.10'
      - name: package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.pip
            /var/cache/apt
          key: jedis-${{hashFiles('**/pom.xml')}}
      - name: install test dependencies
        run: |
          pip install --upgrade setuptools pip
          pip install -r pytest/requirements.txt
      - name: run tests
        run: make test
      - name: codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
